### PR TITLE
Rename sourceName parameter to objectName in DownloadObject

### PR DESCRIPTION
**Pull request by jskeet**

### CODE REVIEW

**Comment by ivannaranjo** [comment]
For what is worth in the API it is referred to as `bucket` and `name`, together forming what I guess is the full name of the object.

**Comment by jskeet** [comment]
As Chris pointed out, the "get" request on Object actually uses "object" as the parameter name:

https://cloud.google.com/storage/docs/json_api/v1/objects/get

The idea is that `objectName` is a good bridge between the two :) If it had just been called `name` there, I'd have used `name` too.

(Admittedly we're not directly using that API, we're using the media API, but it's conceptually like that...)

**Comment by ivannaranjo** [comment]
Ah, I was looking at https://cloud.google.com/storage/docs/json_api/v1/objects/insert, which indeed uses `name` instead. I guess that API is not even consistent with itself. Sight... Ok, then I think it makes sense to call it `objectName`, my objection is retracted. Ship it, :shipit: :+1:

**Comment by Capstan** [comment]
You folks are the first to point out that oddity. The URL path is shared among other resources, e.g., [storage.objectsAccessControls.get](https://cloud.google.com/storage/docs/json_api/v1/objectAccessControls/get), and for homogeneity there, we use `object` as the parameter. Within the metadata of the object itself, calling the name `objectName` seemed redundant. Then last, the case where you're trying to upload a raw file but because the URL for the operation is a POST to the collection and thus doesn't have the object name, we chose the metadata name rather than the collection instance name.

**Pull request merged**
