### PR TITLE
Fix demo launch configuration

### PR DESCRIPTION
**Pull request by jskeet**
I'd failed to do this properly when changing the namespace.

### CODE REVIEW

**Comment by csells** [comment]
Has this demo been changed to target .NET 4.x?

**Comment by jskeet** [comment]
It was already targeting .NET 4.5.1. It won't work with .NET Core yet.

**Comment by jskeet** [comment]
(This change is just about getting F5 to work in VS.)

**Comment by csells** [comment]
The package restore fails when loading from VS2015 update 2:

PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\External\git
C:\Users\Chris\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\dnx.exe "C:\Users\Chris\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1\bin\lib\Microsoft.Dnx.Tooling\Microsoft.Dnx.Tooling.dll" restore "C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\test\Google.Storage.V1.IntegrationTests" "C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\test\Google.Storage.V1.Tests" "C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\demo\Google.Pubsub.V1.Demo" "C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Logging.V2" "C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Logging.Type" "C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Datastore.V1Beta3" "C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Storage.V1" "C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\demo\Google.Storage.V1.Demo" "C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Pubsub.V1" "C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\demo\Google.Datastore.V1Beta3.Demo" "C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\test\Google.Datastore.V1Beta3.Tests" -f "C:\Program Files (x86)\Microsoft Web Tools\DNU"
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16231
  CACHE https://api.nuget.org/v3/index.json
  CACHE https://www.myget.org/F/google-dotnet-public/api/v3/index.json
Restoring packages for C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\test\Google.Storage.V1.IntegrationTests\project.json
Writing lock file C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\test\Google.Storage.V1.IntegrationTests\project.lock.json
Restore complete, 2819ms elapsed
Restoring packages for C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\test\Google.Storage.V1.Tests\project.json
Writing lock file C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\test\Google.Storage.V1.Tests\project.lock.json
Restore complete, 151ms elapsed
Restoring packages for C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\demo\Google.Pubsub.V1.Demo\project.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.framework.commandlineutils.sources/index.json
  GET https://www.myget.org/F/google-dotnet-public/api/v3/flatcontainer/microsoft.framework.commandlineutils.sources/index.json
Warning: FindPackagesById: Microsoft.Framework.CommandLineUtils.Sources
  An error occurred while sending the request.
Warning: FindPackagesById: Microsoft.Framework.CommandLineUtils.Sources
  An error occurred while sending the request.
  GET https://www.myget.org/F/google-dotnet-public/api/v3/flatcontainer/microsoft.framework.commandlineutils.sources/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.framework.commandlineutils.sources/index.json
Warning: FindPackagesById: Microsoft.Framework.CommandLineUtils.Sources
  An error occurred while sending the request.
Warning: FindPackagesById: Microsoft.Framework.CommandLineUtils.Sources
  An error occurred while sending the request.
  GET https://www.myget.org/F/google-dotnet-public/api/v3/flatcontainer/microsoft.framework.commandlineutils.sources/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.framework.commandlineutils.sources/index.json
Error: FindPackagesById: Microsoft.Framework.CommandLineUtils.Sources
  An error occurred while sending the request.
Error: FindPackagesById: Microsoft.Framework.CommandLineUtils.Sources
  An error occurred while sending the request.
----------
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'www.myget.org'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.Restore.NuGet.HttpSource.<GetAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.Restore.NuGet.NuGetv3Feed.<FindPackagesByIdAsyncCore>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RemoteWalkProvider.<FindLibrary>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibrary>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryByVersion>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryMatch>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<CreateGraphNode>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
An error occurred while sending the request.
Restoring packages for C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Logging.V2\project.json
Writing lock file C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Logging.V2\project.lock.json
Restore complete, 608ms elapsed
Restoring packages for C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Logging.Type\project.json
Writing lock file C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Logging.Type\project.lock.json
Restore complete, 438ms elapsed
Restoring packages for C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Datastore.V1Beta3\project.json
Writing lock file C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Datastore.V1Beta3\project.lock.json
Restore complete, 375ms elapsed
Restoring packages for C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Storage.V1\project.json
Writing lock file C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Storage.V1\project.lock.json
Restore complete, 378ms elapsed
Restoring packages for C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\demo\Google.Storage.V1.Demo\project.json
----------
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The remote name could not be resolved: 'api.nuget.org'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.Restore.NuGet.HttpSource.<GetAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.Restore.NuGet.NuGetv3Feed.<FindPackagesByIdAsyncCore>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RemoteWalkProvider.<FindLibrary>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibrary>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryByVersion>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryMatch>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<CreateGraphNode>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
An error occurred while sending the request.
Restoring packages for C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Pubsub.V1\project.json
Writing lock file C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\src\Google.Pubsub.V1\project.lock.json
Restore complete, 295ms elapsed
Restoring packages for C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\demo\Google.Datastore.V1Beta3.Demo\project.json
Writing lock file C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\demo\Google.Datastore.V1Beta3.Demo\project.lock.json
Restore complete, 271ms elapsed
Restoring packages for C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\test\Google.Datastore.V1Beta3.Tests\project.json
Writing lock file C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\test\Google.Datastore.V1Beta3.Tests\project.lock.json
Restore complete, 1077ms elapsed
NuGet Config files used:
    C:\Users\Chris\AppData\Roaming\NuGet\nuget.config
    C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\nuget.config
    C:\Users\Chris\AppData\Roaming\NuGet\nuget.config
    C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\nuget.config
    C:\Users\Chris\AppData\Roaming\NuGet\nuget.config
    C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\nuget.config
    C:\Users\Chris\AppData\Roaming\NuGet\nuget.config
    C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\nuget.config
    C:\Users\Chris\AppData\Roaming\NuGet\nuget.config
    C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\nuget.config
    C:\Users\Chris\AppData\Roaming\NuGet\nuget.config
    C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\nuget.config
    C:\Users\Chris\AppData\Roaming\NuGet\nuget.config
    C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\nuget.config
    C:\Users\Chris\AppData\Roaming\NuGet\nuget.config
    C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\nuget.config
    C:\Users\Chris\AppData\Roaming\NuGet\nuget.config
    C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\nuget.config
    C:\Users\Chris\AppData\Roaming\NuGet\nuget.config
    C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\nuget.config
    C:\Users\Chris\AppData\Roaming\NuGet\nuget.config
    C:\Users\Chris\Downloads\gcloud-dotnet-fix-demo\gcloud-dotnet-fix-demo\nuget.config
Feeds used:
    https://api.nuget.org/v3-flatcontainer/
    https://www.myget.org/F/google-dotnet-public/api/v3/flatcontainer/
    C:\Program Files (x86)\Microsoft Web Tools\DNU

**Comment by csells** [comment]
the restore failure looks like a temp. network problem. this change lgtm.

**Pull request merged**
