### PR TITLE
Preparing for first nuget.org release

### PR DESCRIPTION
**Pull request by jskeet**
(It's probably worth looking at the two commits separately)

### CODE REVIEW

**Comment by ivannaranjo** [comment]
It looks good to me. The only nagging thought in my mind is your dependency on `DNX RC1 Update 1` which I think is fine for an alpha but might not be for a ga.
:shipit:

**Comment by jskeet** [comment]
Unfortunately, it's failing on MyGet at the moment, and I don't understand why:

> error CS1705: Assembly 'Google.Apis' with identity 'Google.Apis, Version=1.10.0.25332, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' uses 'Google.Apis.Core, Version=1.10.0.25331, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab' which has a higher version than referenced assembly 'Google.Apis.Core' with identity 'Google.Apis.Core, Version=1.10.0.0, Culture=neutral, PublicKeyToken=4b01fa6e34db77ab'

I don't get that locally, although I get a *warning* which is different:

> warning NU1007: Dependency specified was Google.Apis.Storage.v1 >= 1.10.0 but ended up with Google.Apis.Storage.v1 1.10.0.362

That warning looks weird to me - surely 1.10.0.362 satisties ">= 1.10.0" with no problems, doesn't it?

**Comment by chrsmith** [comment]
@mmdriley has more context on the assembly resolution woes related to the client libraries.

**Comment by jskeet** [comment]
Myget failure now understood - and in different branch anyway :) Will merge this.

**Pull request merged**
