### PR TITLE
Preconditions usage

### PR DESCRIPTION
**Pull request by jskeet**

### CODE REVIEW

**Comment by ivannaranjo** [comment]
Looks quite good. I think that the issue is that you have to ensure that all the sources are present of all of the projects and call `dnu restore --parallel` at the top of the project tree, the `src` folder. That should ensure all of the projects are ready to use.

**Comment by jskeet** [comment]
They're all in the same repo, so I think it unlikely that someone would have some projects but not others. When we've pushed Google.Common.Embeddable to NuGet, it won't be an issue, of course, and we can remove this.

**Comment by jskeet** [comment]
I've rebased this against #8; it now has fewer changes in it.
Ready to commit when #8 is in, assuming you're still happy @ivannaranjo.

**Comment by jskeet** [comment]
Okay, so it looks like dnu restore only works from the solution directory at the moment. This is ugly, but is a way of making forward progress. @ivannaranjo - ready for a merge?

**Comment by ivannaranjo** [comment]
Sure, dnu restore should work from any directory though, it looks for
project.json in nested directories wherever they are.

**Comment by jskeet** [comment]
Yup, it looks for project.json in a nested way... but how it treats the "projects" entry in global.json changes depending on where it's invoked. It all seems odd to me, but hopefully it's just a temporary issue... Merging now, and then I can get on with some features...

**Pull request merged**
